# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

app = QtWidgets.QApplication([])

dict = {
    0: (2, 5, 1, 2),
    1: (2, 0, 1, 2),
    2: (0, 2, 1, 3),
    3: (3, 1, 1, 2),
    4: (4, 3, 1, 2),
    5: (4, 2, 1, 3),
    6: (1, 1, 1, 2),
    7: (0, 3, 1, 2),

    8: (2, 2, 1, 3),  # central image

    9: (3, 4, 1, 2),
    10: (1, 4, 1, 2),
    11: (2, 5, 1, 2),
    12: (4, 5, 1, 2)
}

labl_list = []
path_to_img = "logo_ico.ico"
pixmap = QtGui.QPixmap(path_to_img)

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("MainWindow")
        self.resize(800, 600)
        
        self.centralwidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 80, 601, 381))

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)

        for i in range(13):
            labl = QtWidgets.QLabel(self.gridLayoutWidget)
            labl.setScaledContents(True)
            self.gridLayout.addWidget(labl, dict[i][0], dict[i][1], dict[i][2], dict[i][3])
            labl_list.append(labl)

        self.setCentralWidget(self.centralwidget)
        self.retranslateUi(self)

    def retranslateUi(self, MainWindow):
        for i in range(12):
            labl_list[i].setPixmap(pixmap)
            labl_list[i].setFixedSize(50, 50)

        labl_list[8].setPixmap(pixmap)
        labl_list[8].setFixedSize(150, 150)

exx = Ui_MainWindow()
exx.show()
app.exec()